-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE cardapios_id_seq;

CREATE SEQUENCE cardapios_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE comandas_id_seq;

CREATE SEQUENCE comandas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE itens_id_seq;

CREATE SEQUENCE itens_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE mesas_id_seq;

CREATE SEQUENCE mesas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pedidos_id_seq;

CREATE SEQUENCE pedidos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE usuarios_id_seq;

CREATE SEQUENCE usuarios_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.cardapios definition

-- Drop table

-- DROP TABLE cardapios;

CREATE TABLE cardapios (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	CONSTRAINT cardapios_pkey PRIMARY KEY (id)
);


-- public.mesas definition

-- Drop table

-- DROP TABLE mesas;

CREATE TABLE mesas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	numero int4 NOT NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT mesas_pkey PRIMARY KEY (id),
	CONSTRAINT ukj0e0hutvqcecq56ogqll8feqw UNIQUE (numero)
);


-- public.usuarios definition

-- Drop table

-- DROP TABLE usuarios;

CREATE TABLE usuarios (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE cardapios_id_seq;

CREATE SEQUENCE cardapios_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE comandas_id_seq;

CREATE SEQUENCE comandas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE itens_id_seq;

CREATE SEQUENCE itens_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE mesas_id_seq;

CREATE SEQUENCE mesas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pedidos_id_seq;

CREATE SEQUENCE pedidos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE usuarios_id_seq;

CREATE SEQUENCE usuarios_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.cardapios definition

-- Drop table

-- DROP TABLE cardapios;

CREATE TABLE cardapios (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	CONSTRAINT cardapios_pkey PRIMARY KEY (id)
);


-- public.mesas definition

-- Drop table

-- DROP TABLE mesas;

CREATE TABLE mesas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	numero int4 NOT NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT mesas_pkey PRIMARY KEY (id),
	CONSTRAINT ukj0e0hutvqcecq56ogqll8feqw UNIQUE (numero)
);


-- public.usuarios definition

-- Drop table

-- DROP TABLE usuarios;

CREATE TABLE usuarios (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	senha varchar(255) NOT NULL,
	cpf varchar(255) NOT NULL,
	tipo_usuario varchar(255) NOT NULL,
	CONSTRAINT usuarios_cpf_key UNIQUE (cpf),
	CONSTRAINT usuarios_email_key UNIQUE (email),
	CONSTRAINT usuarios_pkey PRIMARY KEY (id),
	CONSTRAINT usuarios_tipo_usuario_check CHECK (((tipo_usuario)::text = ANY ((ARRAY['ADMIN'::character varying, 'GARCOM'::character varying, 'COZINHEIRO'::character varying, 'BARMAN'::character varying])::text[])))
);


-- public.funcionarios definition

-- Drop table

-- DROP TABLE funcionarios;

CREATE TABLE funcionarios (
	usuario_id int8 NOT NULL,
	matricula varchar(255) NOT NULL,
	data_admissao date NOT NULL,
	salario numeric(10,2) NULL,
	CONSTRAINT funcionarios_matricula_key UNIQUE (matricula),
	CONSTRAINT funcionarios_pkey PRIMARY KEY (usuario_id),
	CONSTRAINT funcionarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


-- public.garcons definition

-- Drop table

-- DROP TABLE garcons;

CREATE TABLE garcons (
	bonus numeric(10,2) NULL,
	funcionario_id int8 NOT NULL,
	CONSTRAINT garcons_pkey PRIMARY KEY (funcionario_id),
	CONSTRAINT fkoqjn5xuyvky3sujt89j8qtxo3 FOREIGN KEY (funcionario_id) REFERENCES funcionarios(usuario_id)
);


-- public.itens definition

-- Drop table

-- DROP TABLE itens;

CREATE TABLE itens (
	id bigserial NOT NULL,
	cardapio_id int8 NOT NULL,
	nome varchar(255) NOT NULL,
	preco numeric(10,2) NOT NULL,
	categoria varchar(255) DEFAULT 'NORMAL'::character varying NOT NULL,
	CONSTRAINT itens_categoria_check CHECK (((categoria)::text = ANY (ARRAY[('NORMAL'::character varying)::text, ('PREMIUM'::character varying)::text, ('BEBIDA'::character varying)::text, ('DRINK'::character varying)::text, ('DRINKS'::character varying)::text]))),
	CONSTRAINT itens_nome_key UNIQUE (nome),
	CONSTRAINT itens_pkey PRIMARY KEY (id),
	CONSTRAINT itens_cardapio_id_fkey FOREIGN KEY (cardapio_id) REFERENCES cardapios(id)
);


-- public.admins definition

-- Drop table

-- DROP TABLE admins;

CREATE TABLE admins (
	funcionario_id int8 NOT NULL,
	nivel_acesso int4 DEFAULT 1 NOT NULL,
	CONSTRAINT admins_funcionario_id_fkey FOREIGN KEY (funcionario_id) REFERENCES funcionarios(usuario_id) ON DELETE CASCADE
);


-- public.comandas definition

-- Drop table

-- DROP TABLE comandas;

CREATE TABLE comandas (
	id bigserial NOT NULL,
	status varchar(255) DEFAULT 'ABERTA'::character varying NOT NULL,
	nome varchar(255) NOT NULL,
	data_abertura timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	data_fechamento timestamp NULL,
	taxaservico bool DEFAULT true NULL,
	valortotal numeric(10,2) NOT NULL,
	garcom_id int8 NOT NULL,
	mesa_id int8 NOT NULL,
	CONSTRAINT comandas_pkey PRIMARY KEY (id),
	CONSTRAINT fk7eduyhifg1dnth8t4cmule52j FOREIGN KEY (garcom_id) REFERENCES garcons(funcionario_id),
	CONSTRAINT fklsihfserb4hx4jdgx2sslp66b FOREIGN KEY (mesa_id) REFERENCES mesas(id)
);


-- public.cozinheiros definition

-- Drop table

-- DROP TABLE cozinheiros;

CREATE TABLE cozinheiros (
	status varchar(255) NOT NULL,
	funcionario_id int8 NOT NULL,
	CONSTRAINT cozinheiros_pkey PRIMARY KEY (funcionario_id),
	CONSTRAINT fkfa7lj3419k2prj8t5uisuh83l FOREIGN KEY (funcionario_id) REFERENCES funcionarios(usuario_id)
);


-- public.barmen definition

-- Drop table

-- DROP TABLE barmen;

CREATE TABLE barmen (
	status varchar(255) NOT NULL,
	funcionario_id int8 NOT NULL,
	CONSTRAINT barmen_pkey PRIMARY KEY (funcionario_id),
	CONSTRAINT fk_barmen_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(usuario_id)
);


-- public.pedidos definition

-- Drop table

-- DROP TABLE pedidos;

CREATE TABLE pedidos (
	id bigserial NOT NULL,
	quantidade int4 NOT NULL,
	obs varchar(255) NULL,
	status varchar(255) NOT NULL,
	comanda_id int8 NOT NULL,
	cozinheiro_id int8 NULL,
	garcom_id int8 NULL,
	barman_id int8 NULL,
	item_id int8 NULL,
	CONSTRAINT pedidos_pkey PRIMARY KEY (id),
	CONSTRAINT fk5er4lbctm2dtpr3cm43ojh6cj FOREIGN KEY (cozinheiro_id) REFERENCES cozinheiros(funcionario_id),
	CONSTRAINT fkc00cmalk5mgn5a6mdh7576vs FOREIGN KEY (garcom_id) REFERENCES garcons(funcionario_id),
	CONSTRAINT fk_pedidos_barman FOREIGN KEY (barman_id) REFERENCES barmen(funcionario_id),
	CONSTRAINT fkt39xl9h0m4akhi3jvki0e94bv FOREIGN KEY (comanda_id) REFERENCES comandas(id),
	CONSTRAINT fktcydoj9tljthvdd2s385t5apc FOREIGN KEY (item_id) REFERENCES itens(id)
);